# Generated by Django 4.1.7 on 2023-03-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_account_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(blank='', default='', max_length=254),
        ),
        migrations.AddField(
            model_name='account',
            name='fullname',
            field=models.TextField(blank='', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='location',
            field=models.TextField(blank='', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='sdt',
            field=models.TextField(blank='', null=True),
        ),
    ]
