# Generated by Django 4.1.7 on 2023-03-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_checkout',
            field=models.BooleanField(null=True),
        ),
    ]
