# Generated by Django 4.1.7 on 2023-03-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_is_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_checkout',
            field=models.BooleanField(choices=[(True, 'Đã thanh toán'), (False, 'Chưa thanh toán')], default=False, null=True),
        ),
    ]
